-
    title: "Permanent Record"
    author: Edward Snowden
    img: https://images-na.ssl-images-amazon.com/images/I/51z1ZaEn6sL._SX327_BO1,204,203,200_.jpg    
    comment: “Edward Snowden's autobiography and story of how and why he exposed the US governments mass surveillance system of the internet.” 
    links:
        -
            type: Amazon
            link: https://amzn.com/1250237238

-
    title: "Sandworm: A New Era of Cyberwar and the Hunt for the Kremlin's Most Dangerous Hackers"
    author: Andy Greenberg
    img: https://images-na.ssl-images-amazon.com/images/I/613VM4hOVNL._SX329_BO1,204,203,200_.jpg    
    comment: “From Wired senior writer Andy Greenberg comes the true story of the most devastating cyberattack in history and the desperate hunt to identify and track the elite Russian agents behind it.” 
    links:
        -
            type: Amazon
            link: https://amzn.com/0385544405

-
    title: "Unmasking the Social Engineer"
    author: Chris Hadnagy
    img: https://images-na.ssl-images-amazon.com/images/I/515b75fHQ3L._SX331_BO1,204,203,200_.jpg
    comment: “The Human Element of Security focuses on combining the science of understanding non-verbal communications with the knowledge of how social engineers, scam artists and con men use these skills to build feelings of trust and rapport in their targets.” 
    links:
        -
            type: Amazon
            link: https://amzn.com/1118608577

-
    title: "Click Here to Kill Everybody: Security and Survival in a Hyper-connected World"
    author: Bruce Schneier
    img: https://images-na.ssl-images-amazon.com/images/I/5199NYWvceL._SY346_B01,204,203,200_.jpg
    comment: \"Everything is a computer. Ovens are computers that make things hot; refrigerators are computers that keep things cold. These computers—from home thermostats to chemical plants—are all online. The Internet, once a virtual abstraction, can now sense and touch the physical world.\" This book is about the inherrent security issues in the Internet of Things. 
    links:
        -
            type: Amazon
            link: https://amzn.com/B07BLMQKZK
            
-
    title: "The Art of Deception: Controlling the Human Element of Security"
    author: Kevin Mitnick
    img: https://images-na.ssl-images-amazon.com/images/I/41QLfYlRxWL._SX331_BO1,204,203,200_.jpg
    comment: In-depth discussion of the techniques of social engineering and how
        to educate your organization to be less susceptible to these attacks.
    links:
        -
            type: Amazon
            link: https://amzn.com/076454280X

-
    title: "Beyond Fear: Thinking Sensibly About Security in an Uncertain World"
    author: Bruce Schneier
    img: https://images-na.ssl-images-amazon.com/images/I/51rusyx0X6L._SX352_BO1,204,203,200_.jpg
    comment: This book is about national security, terrorism, and how to think sensibly about whether security measures are worth the cost to society
    links:
      -
        type: Amazon
        link: https://amzn.com/1475781199

-
    title: "Countdown to Zero Day: Stuxnet and the Launch of the World's First
        Digital Weapon"
    author: Kim Zetter
    img: https://images-na.ssl-images-amazon.com/images/I/61XdPxNxKdL._SX322_BO1,204,203,200_.jpg
    comment: Interesting and compelling read about the discovery of Stuxnet and
        how it changed the world.
    links:
        -
            type: Amazon
            link: https://amzn.com/077043617X

-
    title: "Crypto: How the Code Rebels Beat the Government Saving Privacy in
        the Digital Age"
    author: Steven Levy
    img: https://images-na.ssl-images-amazon.com/images/I/41Tuv9saPgL._SX323_BO1,204,203,200_.jpg
    comment: A very engaging look at the modern history of cryptography, including
        the development of DES, RSA, and PGP. Also, it describes the fight in
        the 1990's to legalize the use of strong cryptography.
    links:
        -
            type: Amazon
            link: https://amzn.com/0140244328

-
    title: "The Cuckoo's Egg: Tracking a Spy Through the Maze of Computer Espionage"
    author: Cliff Stoll
    img: https://images-na.ssl-images-amazon.com/images/I/51sSd8%2BSI7L._SX320_BO1,204,203,200_.jpg
    comment: Classic security novel &ndash; the true story of how a network admin got caught up in global computer espionage using network security monitoring. Reads like a thriller.
    links:
      -
        type: Amazon
        link: https://amzn.com/1416507787

-
    title: "Data and Goliath: The Hidden Battles to Collect your Data and Control your World"
    author: "Bruce Schneier"
    img: https://images-na.ssl-images-amazon.com/images/I/51fMr8ndNjL._SX330_BO1,204,203,200_.jpg
    comment: Great book about the threats of surveillance to society, and what we can do about it. After reading the book, you probably won't view surveillance the same way again.
    links:
      -
        type: Amazon
        link: https://amzn.com/0393244814

-
    title: "Dragnet Nation: A Quest for Privacy, Security, and Freedom in a
        World of Relentless Surveillance"
    author: Julia Angwin
    img: https://images-na.ssl-images-amazon.com/images/I/51zYxbbNIEL._SX329_BO1,204,203,200_.jpg
    comment: Award-winning journalist Julia Angwin reports from the front lines of
        America’s surveillance economy, offering a revelatory and unsettling
        look at how the government, private companies, and even criminals
        use technology to indiscriminately sweep up vast amounts of our
        personal data.
    links:
        -
            type: Amazon
            link: https://amzn.com/0805098070

-
    title: "Ghost in the Wires: My Adventures as the World's Most Wanted Hacker"
    author: Kevin Mitnick
    img: https://images-na.ssl-images-amazon.com/images/I/51kt5CfVEkL._SX330_BO1,204,203,200_.jpg
    comment: Autobiography of Kevin Mitnick, famed computer hacker and social
        engineer. In addition to being a very entertaining and fascinating read,
        you'll learn a lot about social engineering techniques from the accounts
        of his experiences.
    links:
        -
            type: Amazon
            link: https://amzn.com/0316037729

-
    title: "Keys to the Kingdom: Impressioning, Privilege Escalation, Bumping,
        and Other Key-Based Attacks Against Physical Locks"
    author: Deviant Ollam
    img: https://images-na.ssl-images-amazon.com/images/I/41gsD-%2BmOxL._SX403_BO1,204,203,200_.jpg
    comment: Another great and accessible book on more advanced lock-picking
        by Deviant Ollam.
    links:
        -
            type: Amazon
            link: https://amzn.com/1597499838



-
    title: "Kingpin: How One Hacker Took Over the Billion-Dollar Cybercrime Underground"
    author: Kevin Poulsen
    img: https://images-na.ssl-images-amazon.com/images/I/51nurgDkpjL._SX321_BO1,204,203,200_.jpg
    links:
        -
            type: Amazon
            link: https://amzn.com/0307588696


-
    title: "Liars and Outliers: Enabling the Trust that Society Needs to Thrive"
    author: Bruce Schneier
    img: https://images-na.ssl-images-amazon.com/images/I/51hv65XhLcL._SX331_BO1,204,203,200_.jpg
    comment: Interesting book about how security enables trust that society needs to function.
    links:
      -
        link: https://amzn.com/1118143302
        type: Amazon

-
    title: "Nothing to Hide: The False Tradeoff Between Privacy and Security"
    author: Daniel Solove
    img: https://images-na.ssl-images-amazon.com/images/I/41aA6ka8BcL._SX385_BO1,204,203,200_.jpg
    comment: A book that debunks the most common attack to privacy arguments.
    links:
        -
            type: Amazon
            link: https://amzn.com/0674035070

-
    title: "Practical Lock Picking, Second Edition: A Physical Penetration
        Tester’s Training Guide"
    author: Deviant Ollam
    img: https://images-na.ssl-images-amazon.com/images/I/415uyWgdtHL._SX404_BO1,204,203,200_.jpg
    comment: The best book available to learn lock-picking.
    links:
        -
            type: Amazon
            link: https://amzn.com/1597499897


-
    title: "Secrets and Lies: Digital Security in a Networked World"
    author: Bruce Schneier
    img: https://images-na.ssl-images-amazon.com/images/I/51GKbAsPEmL._SX328_BO1,204,203,200_.jpg
    comment: Excellent overview of information security, from cryptography to authentication to the human factor
    links:
      -
        type: Amazon
        link: https://amzn.com/0471453803

-
    title: "Social Engineering: The Art of Human Hacking"
    author: Christopher Hadnagy
    img: https://images-na.ssl-images-amazon.com/images/I/41HpNgCrStL._SX332_BO1,204,203,200_.jpg
    comment: Another well-regarded book on social engineering, from the
        organization that operates the Social Engineer Village at DEF CON.
    links:
        -
            type: Amazon
            link: https://amzn.com/0470639539

-
    title: "Spam Nation: The Inside Story of Organized Cybercrime-from Global
        Epidemic to Your Front Door"
    author: Brian Krebs
    img: https://images-na.ssl-images-amazon.com/images/I/51bqPI0%2BRQL.jpg
    comment: In _Spam Nation_, investigative journalist Brian Krebs unmasks the
         criminal masterminds driving some of the biggest spam and hacker
         operations targeting Americans and their bank accounts. Tracing the
         rise, fall, and alarming resurrection of the digital mafia behind the two
         largest spam pharmacies-and countless viruses, phishing, and
         spyware attacks-he delivers the first definitive narrative of the global
         spam problem and its threat to consumers everywhere.
    links:
        -
            type: Amazon
            link: https://amzn.com/0805098070

-
    title: The Code Book
    author: Simon Singh
    img: https://images-na.ssl-images-amazon.com/images/I/51S0aQLkDCL._SX324_BO1,204,203,200_.jpg
    comment: This is a very interesting and gripping book about the history and
        intrigue of cryptography and cryptanalysis.
    links:
        -
            type: Amazon
            link: https://amzn.com/0470474246

-
    title: The Practice of Network Security Monitoring
    author: Richard Beljtlich
    img: https://images-na.ssl-images-amazon.com/images/I/518TRuafy3L._SX376_BO1,204,203,200_.jpg
    comment: Excellent book on the principles of NSM and how to get started with
        Security Onion.
    links:
        -
            type: Amazon
            link: https://amzn.com/1593275099